baseURL = 'https://radusz.com'
languageCode = 'en-us'
title = 'théo raduszynski'
theme = 'hugo-bearblog'

[params]
  blog_description = "personal page and some reflections"
  hideMadeWithLine = true

[Author]
  name = "Théo Raduszynski"
  email  = "theo@radusz.com"

[outputs]
  home = ['html']
  section = ['html']
  taxonomy = ['html']
  term = ['html']